{% set name = "msgfy" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37c907cccb19afe73ce44111a21b410b685be92c9c44496bc4381fd93c5ad7b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - releasecmd
  run:
    - python >=3.5

test:
  imports:
    - msgfy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/msgfy
  summary: msgfy is a Python library for convert Exception instance to a human-readable error message.
  dev_url: https://github.com/thombashi/msgfy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
